/**
 * Example usage of numpy library.
 * Generating, normalizing, filtering and stacking matrix.
 *

In [4]:
import numpy as np
X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print(X)

[[  2.38994738  -9.87853891   6.95218321 ..., -12.83911918  27.83506339
  -21.77459246]
 [-11.07093994 -11.94294695  18.77568187 ...,  -7.52952477  -1.72648355
   -3.05705055]
 [ -1.91804939 -12.01522934  10.66305041 ...,   6.38057349   2.52195525
   -5.85156692]
 ..., 
 [ -2.57891554   2.39420165  -1.09950259 ...,  -0.53632421  -9.81827677
   -9.58166447]
 [ -9.55393844  -1.9421095    9.69739554 ...,  -6.898125    17.88044798
    2.71299891]
 [  9.85609898   2.8262623  -18.97920417 ...,   3.9720101   -9.35723691
   -4.84409833]]


In [5]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m)  / std)
print(X_norm)

[[ 0.17221423 -0.9991891   0.62342277 ..., -1.39037616  2.79935071
  -2.34206756]
 [-1.15905153 -1.20404144  1.77361487 ..., -0.85990014 -0.25506412
  -0.45301675]
 [-0.25384153 -1.21121406  0.98441661 ...,  0.52984324  0.18390122
  -0.73505076]
 ..., 
 [-0.31920041  0.21864164 -0.15984669 ..., -0.16121678 -1.09113989
  -1.11150744]
 [-1.00902188 -0.21165288  0.89047752 ..., -0.79681764  1.77080085
   0.12932022]
 [ 0.91060775  0.26151526 -1.8991873  ...,  0.28920619 -1.04350345
  -0.63337291]]


In [6]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

r = np.sum(Z, axis=1)
print(np.nonzero(r > 10))

(array([1, 4, 5], dtype=int64),)


In [8]:
A = np.eye(3)
B = np.eye(3)
print(A)
print(B)

AB = np.vstack((A, B))
print(AB)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
